import { Link } from "react-router-dom";
import hero from "../assets/2.jpg";

const FAQS = [
  {
    q: "How do I make a reservation?",
    a: "Go to the “Make Reservation” page, fill your details, choose dates and room type, then submit. You will receive an email confirmation based on the reservation status."
  },
  {
    q: "Can I cancel or change my reservation?",
    a: "Yes. If your reservation is still pending, you can update or cancel it from your account (when account features are enabled). Otherwise, contact the resort support email for assistance."
  },
  {
    q: "Will I receive an email after booking?",
    a: "Yes. The system sends automatic emails for pending/confirmed reservations and important updates."
  },
  {
    q: "Do I need an account to reserve?",
    a: "It depends on your system flow. Typically, registering helps you track and manage reservations. If guest booking is allowed, you can reserve without an account."
  },
  {
    q: "What payment methods are supported?",
    a: "Currently, billing can be generated by the system. Payment integration (card/online payments) can be added as a future enhancement."
  },
  {
    q: "Is my data secure?",
    a: "Yes. The system uses secure authentication and role-based access. Passwords are stored securely, and admin actions are protected."
  }
];

export default function Faq() {
  return (
    <>
      {/* HERO (same style as about-hero classes you already have) */}
      <section className="ov-about-hero">
        <img src={hero} alt="FAQ" className="ov-about-img" />
        <div className="ov-about-overlay" />

        <div className="container ov-about-hero-content">
          <div className="ov-about-hero-box">
            <span className="ov-about-kicker">HELP CENTER</span>
            <h1 className="ov-about-title">
              Frequently Asked <span className="accent">Questions</span>
            </h1>
            <p className="ov-about-sub">
              Quick answers about reservations, emails, billing, and system access.
            </p>

            <div className="d-flex gap-2 flex-wrap mt-3">
              <span className="ov-about-pill">Reservations</span>
              <span className="ov-about-pill">Emails</span>
              <span className="ov-about-pill">Billing</span>
              <span className="ov-about-pill">Security</span>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ CONTENT */}
      <section className="ov-about-section">
        <div className="container">
          <div className="row g-4">
            {/* LEFT: FAQ LIST */}
            <div className="col-12 col-lg-8">
              <div className="ov-card-soft">
                <div className="d-flex align-items-center justify-content-between gap-3 flex-wrap">
                  <h2 className="ov-h2 mb-0">FAQs</h2>

                  <Link to="/customer/reservations" className="btn ov-btn-dark">
                    Make Reservation
                  </Link>
                </div>

                <div className="ov-divider" />

                <div className="accordion" id="faqAccordion">
                  {FAQS.map((item, idx) => (
                    <div className="accordion-item" key={idx}>
                      <h2 className="accordion-header" id={`h-${idx}`}>
                        <button
                          className={`accordion-button ${idx !== 0 ? "collapsed" : ""}`}
                          type="button"
                          data-bs-toggle="collapse"
                          data-bs-target={`#c-${idx}`}
                          aria-expanded={idx === 0 ? "true" : "false"}
                          aria-controls={`c-${idx}`}
                        >
                          {item.q}
                        </button>
                      </h2>

                      <div
                        id={`c-${idx}`}
                        className={`accordion-collapse collapse ${idx === 0 ? "show" : ""}`}
                        aria-labelledby={`h-${idx}`}
                        data-bs-parent="#faqAccordion"
                      >
                        <div className="accordion-body">
                          <p className="ov-p">{item.a}</p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>

                <p className="ov-form-note mt-3 mb-0">
                  Need more help? You can contact the resort support email from the footer.
                </p>
              </div>
            </div>

            {/* RIGHT: QUICK INFO */}
            <div className="col-12 col-lg-4">
              <div className="ov-card-soft">
                <h4 className="ov-h4 mb-2">Quick Tips</h4>
                <p className="ov-p">
                  Before booking, confirm your dates and room type. Use a valid email to receive
                  confirmation messages.
                </p>

                <div className="ov-divider" />

                <div className="ov-about-stats">
                  <div className="ov-stat">
                    <div className="ov-stat-label">Average Response Time</div>
                    <div className="ov-stat-value">Within 24 hours (Email Support)</div>
                  </div>

                  <div className="ov-stat">
                    <div className="ov-stat-label">Reservation Status</div>
                    <div className="ov-stat-value">Pending → Confirmed</div>
                  </div>

                  <div className="ov-stat">
                    <div className="ov-stat-label">Secure Access</div>
                    <div className="ov-stat-value">Role-based (Admin / Customer)</div>
                  </div>
                </div>

                <div className="ov-divider" />

                <Link to="/about" className="btn ov-btn w-100">
                  Learn More
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* OPTIONAL: DARK CTA SECTION */}
      <section className="ov-about-section ov-about-bg">
        <div className="container">
          <div className="row g-4 align-items-center">
            <div className="col-12 col-lg-7 text-white">
              <h2 className="ov-h2 text-white mb-2">Ready to book your stay?</h2>
              <p className="mb-0" style={{ color: "rgba(255,255,255,0.85)", lineHeight: 1.7 }}>
                Start your reservation in a few steps. Our system will guide you and notify you by email.
              </p>

              <div className="ov-about-help">
                <div className="ov-about-help-item">
                  <i className="bi bi-check-circle-fill" />
                  Fast reservation submission
                </div>
                <div className="ov-about-help-item">
                  <i className="bi bi-envelope-check-fill" />
                  Email confirmation & alerts
                </div>
                <div className="ov-about-help-item">
                  <i className="bi bi-shield-lock-fill" />
                  Secure customer and admin access
                </div>
              </div>
            </div>

            <div className="col-12 col-lg-5">
              <div className="ov-form-card">
                <h4 className="ov-h4 mb-2">Start Now</h4>
                <p className="ov-p mb-3">
                  Click below to create a new reservation.
                </p>

                <Link to="/customer/reservations" className="btn ov-btn-dark w-100">
                  Make Reservation
                </Link>

                <div className="ov-form-note">
                  Tip: Use your correct email to receive confirmation messages.
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}